### ISSUE TITLE
[Kotlindoc] GroovyCastException for kotlindoc.externalDocumentationLinks

### ISSUE THREAD

**Issue by tlinkowski** [aalmiray/kordamp-gradle-plugins#155]
The following configuration:
```
config {
  kotlindoc {
    externalDocumentationLinks { 
      externalDocumentationLink { 
        url = "https://docs.gradle.org/current/javadoc/"
      }
    }
  }
}
```

throws:

```
Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'https://docs.gradle.org/current/javadoc/' with class 'java.lang.String' to class 'java.net.URL'
	at org.kordamp.gradle.plugin.kotlindoc.KotlindocPlugin$_applyConfiguration_closure7$_closure14.doCall(KotlindocPlugin.groovy:218)
	at org.kordamp.gradle.plugin.kotlindoc.KotlindocPlugin$_applyConfiguration_closure7$_closure14.doCall(KotlindocPlugin.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.jetbrains.dokka.gradle.DokkaTask$externalDocumentationLink$1.execute(main.kt:217)
	at org.jetbrains.dokka.gradle.DokkaTask$externalDocumentationLink$1.execute(main.kt:60)
	at org.jetbrains.dokka.gradle.DokkaTask.externalDocumentationLink(main.kt:210)
	at org.jetbrains.dokka.gradle.DokkaTask.externalDocumentationLink(main.kt:215)
	at org.jetbrains.dokka.gradle.DokkaTask$externalDocumentationLink.call(Unknown Source)
	at org.kordamp.gradle.plugin.kotlindoc.KotlindocPlugin$_applyConfiguration_closure7.doCall(KotlindocPlugin.groovy:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.kordamp.gradle.plugin.kotlindoc.KotlindocPlugin.applyConfiguration(KotlindocPlugin.groovy:216)
	at org.kordamp.gradle.plugin.kotlindoc.KotlindocPlugin$applyConfiguration.callStatic(Unknown Source)
	at org.kordamp.gradle.plugin.kotlindoc.KotlindocPlugin.createKotlindocTaskIfNeeded(KotlindocPlugin.groovy:140)
	at org.kordamp.gradle.plugin.kotlindoc.KotlindocPlugin.access$2(KotlindocPlugin.groovy)
	at org.kordamp.gradle.plugin.kotlindoc.KotlindocPlugin$_configureProject_closure2$_closure9$_closure10.doCall(KotlindocPlugin.groovy:108)
	at jdk.internal.reflect.GeneratedMethodAccessor860.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.kordamp.gradle.plugin.kotlindoc.KotlindocPlugin$_configureProject_closure2$_closure9.doCall(KotlindocPlugin.groovy:107)
	at org.kordamp.gradle.plugin.kotlindoc.KotlindocPlugin$_configureProject_closure2$_closure9.call(KotlindocPlugin.groovy)
	[...]
	at org.kordamp.gradle.plugin.kotlindoc.KotlindocPlugin$_configureProject_closure2.doCall(KotlindocPlugin.groovy:103)
	[...]
```

In Dokka, `ExternalDocumentationLink.url` is indeed of type `URL`:
https://github.com/Kotlin/dokka/blob/6a1a0fde56be22c565d10d71f37f84e8d78c212a/integration/src/main/kotlin/org/jetbrains/dokka/configuration.kt#L67

The culprit is here:
https://github.com/aalmiray/kordamp-gradle-plugins/blob/2e39747f6e8cdc494c37db84bda99893682d4d0d/plugins/kotlindoc-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/kotlindoc/KotlindocPlugin.groovy#L216-L221

**Comment by tlinkowski** [comment]
Hi, thanks for the fix! Unfortunately, it doesn't work:
```
Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'https://docs.gradle.org/current/javadoc/' with class 'java.lang.String' to class 'java.net.URL'
	at org.kordamp.gradle.plugin.kotlindoc.KotlindocPlugin$_applyConfiguration_closure7$_closure14.doCall(KotlindocPlugin.groovy:218)
	at org.kordamp.gradle.plugin.kotlindoc.KotlindocPlugin$_applyConfiguration_closure7$_closure14.doCall(KotlindocPlugin.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```

You can't just cast a `String` to an `URL` - instead, you simply need to call [`URL`'s constructor](https://docs.oracle.com/javase/8/docs/api/java/net/URL.html#URL-java.lang.String-) 🙂
